-- create the warehouse for the loading
CREATE OR REPLACE WAREHOUSE HOSPITAL_MANAGEMENT_LOADING
  WITH 
  WAREHOUSE_SIZE = 'XSMALL'           
  AUTO_SUSPEND = 300                      
  AUTO_RESUME = TRUE                        
  INITIALLY_SUSPENDED = TRUE;
-- create the warehouse for the analysis 
CREATE OR REPLACE WAREHOUSE HOSPITAL_MANAGEMENT_ANALYTICS 
  WITH 
  WAREHOUSE_SIZE = 'XSMALL'           
  AUTO_SUSPEND = 300                      
  AUTO_RESUME = TRUE                        
  INITIALLY_SUSPENDED = TRUE;

CREATE OR REPLACE DATABASE HOSPITAL_DATABASE;

CREATE OR REPLACE SCHEMA HOSPITAL_RAW;
CREATE OR REPLACE SCHEMA HOSPITAL_CORE;
CREATE OR REPLACE SCHEMA HOSPITAL_MART;






  