--USE CONTEXT
USE WAREHOUSE HOSPITAL_MANAGEMENT_LOADING;
USE DATABASE HOSPITAL_DATABASE;
USE SCHEMA HOSPITAL_RAW;

-- CREATE THE RAW TABLES 
CREATE OR REPLACE TABLE PATIENT_RAW
(
    PATIENT_ID STRING,
    FULL_NAME STRING,
    DOB DATE,
    GENDER STRING,
    PHONE STRING,
    EMAIL STRING,
    CITY STRING,
    STATE STRING,
    REGISTRATION_DATE DATE
);

CREATE OR REPLACE TABLE APPOINTMENT_RAW(
    APPT_ID STRING,
    APPT_DATE DATE,
    PATIENT_ID STRING,
    DOCTOR_ID STRING,
    DOCTOR_NAME STRING,
    DEPARTMENT STRING,
    SLOT STRING,
    STATUS STRING
);

CREATE OR REPLACE TABLE BILLING_RAW(
    BILL_ID STRING,
    BILL_DATE DATE,
    PATIENT_ID STRING,
    SERVICE_CODE STRING,
    SERVICE_DESC STRING,
    DEPARTMENT STRING,
    GROSS_AMOUNT FLOAT,
    DISCOUNT_AMOUNT FLOAT,
    TAX_AMOUNT FLOAT,
    NET_AMOUNT FLOAT,
    PAYMENT_MODE STRING,
    INSURER_NAME STRING
);

SHOW TABLES;

--CREATE THE 
CREATE OR REPLACE FILE FORMAT CSV_FORMAT
TYPE = CSV
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY='"'
EMPTY_FIELD_AS_NULL=TRUE
TRIM_SPACE=TRUE;

-- CREATE THE EXTERNAL STAGE BY AWS S3

CREATE OR REPLACE STAGE HOSPITAL_S3_STAGE
URL='s3://snowflake01bucket01'
 CREDENTIALS =(
    AWS_KEY_ID=''
    AWS_SECRET_KEY=''
 )
FILE_FORMAT = CSV_FORMAT;

SHOW STAGES;

LIST @HOSPITAL_S3_STAGE;

