--USE CONTEXT
USE WAREHOUSE HOSPITAL_MANAGEMENT_LOADING;
USE DATABASE HOSPITAL_DATABASE;
USE SCHEMA HOSPITAL_RAW;

-- CREATE THE PIPE FOR PATIENT 
CREATE OR REPLACE PIPE PATIENT_PIPE
AUTO_INGEST = TRUE
AS
COPY INTO PATIENT_RAW
FROM @HOSPITAL_S3_STAGE
PATTERN='.*patients_master.*[.]csv'
FILE_FORMAT = CSV_FORMAT;


-- CREATE THE PIPE FOR APPOINTMENT 
CREATE OR REPLACE PIPE APPOINTMENT_PIPE
AUTO_INGEST = TRUE
AS
COPY INTO APPOINTMENT_RAW
FROM @HOSPITAL_S3_STAGE
PATTERN='.*appointments.*[.]csv'
FILE_FORMAT = CSV_FORMAT;


-- CREATE THE PIPE FOR BILLING 
CREATE OR REPLACE PIPE BILLING_PIPE
AUTO_INGEST = TRUE
AS
COPY INTO BILLING_RAW
FROM @HOSPITAL_S3_STAGE
PATTERN='.*billing.*[.]csv'
FILE_FORMAT = CSV_FORMAT;

SHOW PIPES;

SELECT * FROM PATIENT_RAW;
SELECT * FROM APPOINTMENT_RAW;
SELECT * FROM BILLING_RAW;