-- USE CONTEXT
USE WAREHOUSE HOSPITAL_MANAGEMENT_LOADING;
USE DATABASE HOSPITAL_DATABASE;
USE SCHEMA HOSPITAL_RAW;



-- PATIENT STREAM
CREATE OR REPLACE STREAM PATIENT_STREAM
ON TABLE PATIENT_RAW;

-- APPOINTMENT STREAM
CREATE OR REPLACE STREAM APPOINTMENT_STREAM
ON TABLE APPOINTMENT_RAW;

-- BILLING STREAM
CREATE OR REPLACE STREAM BILLING_STREAM
ON TABLE BILLING_RAW;


SHOW STREAMS;



SELECT * FROM PATIENT_STREAM;

SELECT * FROM APPOINTMENT_STREAM;

SELECT * FROM BILLING_STREAM;