-- SET CONTEXT
USE WAREHOUSE HOSPITAL_MANAGEMENT_ANALYTICS;
USE DATABASE HOSPITAL_DATABASE;
USE SCHEMA HOSPITAL_MART;

-- DIMENSION DYNAMIC TABLES

CREATE OR REPLACE DYNAMIC TABLE DIM_PATIENT
TARGET_LAG = '1 MINUTE'
WAREHOUSE = HOSPITAL_MANAGEMENT_ANALYTICS
AS
SELECT DISTINCT
    PATIENT_ID,
    FULL_NAME,
    DOB,
    GENDER,
    PHONE,
    EMAIL,
    CITY,
    STATE,
    REGISTRATION_DATE
FROM HOSPITAL_DATABASE.HOSPITAL_CORE.PATIENT_CORE;

-- create the dynmic doctor table
CREATE OR REPLACE DYNAMIC TABLE DIM_DOCTOR
TARGET_LAG = '1 MINUTE'
WAREHOUSE = HOSPITAL_MANAGEMENT_ANALYTICS
AS
SELECT DISTINCT
    DOCTOR_ID,
    DOCTOR_NAME,
    DEPARTMENT
FROM HOSPITAL_DATABASE.HOSPITAL_CORE.APPOINTMENT_CORE
WHERE DOCTOR_ID IS NOT NULL;

-- FACT DYNAMIC TABLES

CREATE OR REPLACE DYNAMIC TABLE FACT_APPOINTMENT
TARGET_LAG = '1 MINUTE'
WAREHOUSE = HOSPITAL_MANAGEMENT_ANALYTICS
AS
SELECT
    APPT_ID,
    APPT_DATE,
    PATIENT_ID,
    DOCTOR_ID,
    DOCTOR_NAME,
    DEPARTMENT,
    SLOT,
    STATUS
FROM HOSPITAL_DATABASE.HOSPITAL_CORE.APPOINTMENT_CORE;

-- create the DYNAMIC fact table for BILLING
CREATE OR REPLACE DYNAMIC TABLE FACT_BILLING
TARGET_LAG = '1 MINUTE'
WAREHOUSE = HOSPITAL_MANAGEMENT_ANALYTICS
AS
SELECT
    BILL_ID,
    BILL_DATE,
    PATIENT_ID,
    SERVICE_CODE,
    SERVICE_DESC,
    DEPARTMENT,
    GROSS_AMOUNT,
    DISCOUNT_AMOUNT,
    TAX_AMOUNT,
    NET_AMOUNT,
    PAYMENT_MODE,
    INSURER_NAME
FROM HOSPITAL_DATABASE.HOSPITAL_CORE.BILLING_CORE;

-- show DYNAMIC TABLES

SHOW DYNAMIC TABLES;

SELECT COUNT(*) FROM DIM_PATIENT;
SELECT COUNT(*) FROM DIM_DOCTOR;
SELECT COUNT(*) FROM FACT_APPOINTMENT;
SELECT COUNT(*) FROM FACT_BILLING;


-- DEPARTMENT APPOINTMENT SUMMARY TABLE

CREATE OR REPLACE VIEW VW_DEPT_APPT_SUMMARY AS
SELECT
    DEPARTMENT,
    COUNT(*) AS TOTAL_APPOINTMENTS,

    SUM(
        CASE
            WHEN STATUS='Completed'
            THEN 1
            ELSE 0
        END
    ) AS COMPLETED_VISITS,

    SUM(
        CASE
            WHEN STATUS='No-Show'
            THEN 1
            ELSE 0
        END
    ) AS NO_SHOWS,

    ROUND(
        (
            SUM(
                CASE
                    WHEN STATUS='Completed'
                    THEN 1
                    ELSE 0
                END
            ) * 100.0
        ) / NULLIF(COUNT(*),0),
        2
    ) AS COMPLETION_RATE

FROM FACT_APPOINTMENT
GROUP BY DEPARTMENT;

-- DAILY OPD TREND

CREATE OR REPLACE VIEW VW_DAILY_OPD_TREND AS
SELECT
    APPT_DATE,

    COUNT(*) AS DAILY_VISITS,

    SUM(
        CASE
            WHEN STATUS='No-Show'
            THEN 1
            ELSE 0
        END
    ) AS NO_SHOWS,

    ROUND(
        COUNT(*) /
        NULLIF(COUNT(DISTINCT DOCTOR_ID),0),
        2
    ) AS AVG_APPOINTMENTS_PER_DOCTOR

FROM FACT_APPOINTMENT
GROUP BY APPT_DATE;


-- REVENUE BY DEPARTMENT

CREATE OR REPLACE VIEW VW_REVENUE_BY_DEPT AS
SELECT
    DEPARTMENT,

    SUM(GROSS_AMOUNT) AS GROSS_REVENUE,

    SUM(NET_AMOUNT) AS NET_REVENUE,

    ROUND(
        AVG(NET_AMOUNT),
        2
    ) AS AVG_BILL_VALUE

FROM FACT_BILLING
GROUP BY DEPARTMENT;


-- PATIENT UTILIZATION
CREATE OR REPLACE VIEW VW_PATIENT_UTILIZATION AS
SELECT

    P.PATIENT_ID,
    P.FULL_NAME,

    COUNT(DISTINCT A.APPT_ID) AS TOTAL_VISITS,

    MAX(A.APPT_DATE) AS LAST_VISIT_DATE,

    COALESCE(
        SUM(B.NET_AMOUNT),
        0
    ) AS LIFETIME_REVENUE

FROM DIM_PATIENT P
LEFT JOIN FACT_APPOINTMENT A
ON P.PATIENT_ID = A.PATIENT_ID
LEFT JOIN FACT_BILLING B
ON P.PATIENT_ID = B.PATIENT_ID
GROUP BY
P.PATIENT_ID,
P.FULL_NAME;


-- INSURANCE VS SELF PAY MIX

CREATE OR REPLACE VIEW VW_INSURANCE_MIX AS
SELECT

    CASE
        WHEN INSURER_NAME IS NULL
             OR INSURER_NAME = ''
        THEN 'SELF_PAY'
        ELSE 'INSURANCE'
    END AS PAYMENT_CATEGORY,

    COUNT(*) AS TOTAL_BILLS,

    SUM(NET_AMOUNT) AS REVENUE

FROM FACT_BILLING

GROUP BY
CASE
    WHEN INSURER_NAME IS NULL
         OR INSURER_NAME = ''
    THEN 'SELF_PAY'
    ELSE 'INSURANCE'
END;


-- VERIFY VIEWS

SHOW VIEWS;

SELECT * FROM VW_DEPT_APPT_SUMMARY;
SELECT * FROM VW_DAILY_OPD_TREND;
SELECT * FROM VW_REVENUE_BY_DEPT;
SELECT * FROM VW_PATIENT_UTILIZATION;
SELECT * FROM VW_INSURANCE_MIX;

 
-- VERIFY MART DATA

SELECT COUNT(*) FROM DIM_PATIENT;
SELECT COUNT(*) FROM DIM_DOCTOR;
SELECT COUNT(*) FROM FACT_APPOINTMENT;
SELECT COUNT(*) FROM FACT_BILLING;