

USE ROLE ACCOUNTADMIN;

-- =====================================================
-- STEP 1 : CREATE ROLES
-- =====================================================

CREATE OR REPLACE ROLE HOSPITAL_ADMIN_ROLE;

CREATE OR REPLACE ROLE HOSPITAL_DOCTOR_ROLE;

CREATE OR REPLACE ROLE HOSPITAL_FINANCE_ROLE;

-- =====================================================
-- STEP 2 : ASSIGN ROLES TO SYSADMIN
-- =====================================================

GRANT ROLE HOSPITAL_ADMIN_ROLE TO ROLE SYSADMIN;

GRANT ROLE HOSPITAL_DOCTOR_ROLE TO ROLE SYSADMIN;

GRANT ROLE HOSPITAL_FINANCE_ROLE TO ROLE SYSADMIN;

-- =====================================================
-- STEP 3 : WAREHOUSE ACCESS
-- =====================================================

GRANT USAGE
ON WAREHOUSE HOSPITAL_MANAGEMENT_ANALYTICS
TO ROLE HOSPITAL_DOCTOR_ROLE;

GRANT USAGE
ON WAREHOUSE HOSPITAL_MANAGEMENT_ANALYTICS
TO ROLE HOSPITAL_FINANCE_ROLE;

GRANT ALL PRIVILEGES
ON WAREHOUSE HOSPITAL_MANAGEMENT_ANALYTICS
TO ROLE HOSPITAL_ADMIN_ROLE;

-- =====================================================
-- STEP 4 : DATABASE ACCESS
-- =====================================================

GRANT USAGE
ON DATABASE HOSPITAL_DATABASE
TO ROLE HOSPITAL_DOCTOR_ROLE;

GRANT USAGE
ON DATABASE HOSPITAL_DATABASE
TO ROLE HOSPITAL_FINANCE_ROLE;

GRANT ALL PRIVILEGES
ON DATABASE HOSPITAL_DATABASE
TO ROLE HOSPITAL_ADMIN_ROLE;

-- =====================================================
-- STEP 5 : MART SCHEMA ACCESS
-- =====================================================

GRANT USAGE
ON SCHEMA HOSPITAL_DATABASE.HOSPITAL_MART
TO ROLE HOSPITAL_DOCTOR_ROLE;

GRANT USAGE
ON SCHEMA HOSPITAL_DATABASE.HOSPITAL_MART
TO ROLE HOSPITAL_FINANCE_ROLE;

GRANT ALL PRIVILEGES
ON SCHEMA HOSPITAL_DATABASE.HOSPITAL_MART
TO ROLE HOSPITAL_ADMIN_ROLE;

-- =====================================================
-- STEP 6 : DOCTOR ACCESS
-- =====================================================

GRANT SELECT
ON TABLE HOSPITAL_DATABASE.HOSPITAL_MART.DIM_PATIENT
TO ROLE HOSPITAL_DOCTOR_ROLE;

GRANT SELECT
ON TABLE HOSPITAL_DATABASE.HOSPITAL_MART.FACT_APPOINTMENT
TO ROLE HOSPITAL_DOCTOR_ROLE;

GRANT SELECT
ON VIEW HOSPITAL_DATABASE.HOSPITAL_MART.VW_PATIENT_UTILIZATION
TO ROLE HOSPITAL_DOCTOR_ROLE;

GRANT SELECT
ON VIEW HOSPITAL_DATABASE.HOSPITAL_MART.VW_DAILY_OPD_TREND
TO ROLE HOSPITAL_DOCTOR_ROLE;

GRANT SELECT
ON VIEW HOSPITAL_DATABASE.HOSPITAL_MART.VW_DEPT_APPT_SUMMARY
TO ROLE HOSPITAL_DOCTOR_ROLE;

-- =====================================================
-- STEP 7 : FINANCE ACCESS
-- =====================================================

GRANT SELECT
ON TABLE HOSPITAL_DATABASE.HOSPITAL_MART.FACT_BILLING
TO ROLE HOSPITAL_FINANCE_ROLE;

GRANT SELECT
ON VIEW HOSPITAL_DATABASE.HOSPITAL_MART.VW_REVENUE_BY_DEPT
TO ROLE HOSPITAL_FINANCE_ROLE;

GRANT SELECT
ON VIEW HOSPITAL_DATABASE.HOSPITAL_MART.VW_INSURANCE_MIX
TO ROLE HOSPITAL_FINANCE_ROLE;

-- =====================================================
-- STEP 8 : ADMIN ACCESS
-- =====================================================

GRANT ALL PRIVILEGES
ON ALL TABLES IN SCHEMA HOSPITAL_DATABASE.HOSPITAL_MART
TO ROLE HOSPITAL_ADMIN_ROLE;

GRANT ALL PRIVILEGES
ON ALL VIEWS IN SCHEMA HOSPITAL_DATABASE.HOSPITAL_MART
TO ROLE HOSPITAL_ADMIN_ROLE;

GRANT ALL PRIVILEGES
ON FUTURE TABLES IN SCHEMA HOSPITAL_DATABASE.HOSPITAL_MART
TO ROLE HOSPITAL_ADMIN_ROLE;

GRANT ALL PRIVILEGES
ON FUTURE VIEWS IN SCHEMA HOSPITAL_DATABASE.HOSPITAL_MART
TO ROLE HOSPITAL_ADMIN_ROLE;

-- =====================================================
-- STEP 9 : CREATE MASKING POLICIES
-- =====================================================

-- PHONE MASKING

USE DATABASE HOSPITAL_DATABASE;

CREATE OR REPLACE MASKING POLICY MASK_PHONE
AS (VAL STRI;NG)
RETURNS STRING ->
CASE
    WHEN CURRENT_ROLE() IN
    (
        'HOSPITAL_ADMIN_ROLE',
        'HOSPITAL_DOCTOR_ROLE'
    )
    THEN VAL
    ELSE 'XXXXXXXXXX'
END;

--------------------------------------------------------

-- EMAIL MASKING

CREATE OR REPLACE MASKING POLICY MASK_EMAIL
AS (VAL STRING)
RETURNS STRING ->
CASE
    WHEN CURRENT_ROLE() IN
    (
        'HOSPITAL_ADMIN_ROLE',
        'HOSPITAL_DOCTOR_ROLE'
    )
    THEN VAL
    ELSE 'xxxxxx@EMAIL.COM'
END;


-- PATIENT NAME MASKING

CREATE OR REPLACE MASKING POLICY MASK_PATIENT_NAME
AS (VAL STRING)
RETURNS STRING ->
CASE
    WHEN CURRENT_ROLE() = 'HOSPITAL_ADMIN_ROLE'
    THEN VAL
    ELSE 'CONFIDENTIAL'
END;


-- REVENUE MASKING
CREATE OR REPLACE MASKING POLICY MASK_REVENUE
AS (VAL FLOAT)
RETURNS FLOAT ->
CASE
    WHEN CURRENT_ROLE() IN
    (
        'HOSPITAL_ADMIN_ROLE',
        'HOSPITAL_FINANCE_ROLE'
    )
    THEN VAL
    ELSE NULL
END;
-- INSURANCE MASKING

CREATE OR REPLACE MASKING POLICY MASK_INSURANCE
AS (VAL STRING)
RETURNS STRING ->
CASE
    WHEN CURRENT_ROLE() IN
    (
        'HOSPITAL_ADMIN_ROLE',
        'HOSPITAL_FINANCE_ROLE'
    )
    THEN VAL
    ELSE 'MASKED'
END;

-- STEP 10 : APPLY MASKING POLICIES

ALTER TABLE HOSPITAL_DATABASE.HOSPITAL_MART.DIM_PATIENT
MODIFY COLUMN PHONE
SET MASKING POLICY MASK_PHONE;

ALTER TABLE HOSPITAL_DATABASE.HOSPITAL_MART.DIM_PATIENT
MODIFY COLUMN EMAIL
SET MASKING POLICY MASK_EMAIL;

ALTER TABLE HOSPITAL_DATABASE.HOSPITAL_MART.DIM_PATIENT
MODIFY COLUMN FULL_NAME
SET MASKING POLICY MASK_PATIENT_NAME;

ALTER TABLE HOSPITAL_DATABASE.HOSPITAL_MART.FACT_BILLING
MODIFY COLUMN NET_AMOUNT
SET MASKING POLICY MASK_REVENUE;

ALTER TABLE HOSPITAL_DATABASE.HOSPITAL_MART.FACT_BILLING
MODIFY COLUMN INSURER_NAME
SET MASKING POLICY MASK_INSURANCE;

-- STEP 11 : VERIFY ROLES

SHOW ROLES;

SHOW GRANTS TO ROLE HOSPITAL_ADMIN_ROLE;

SHOW GRANTS TO ROLE HOSPITAL_DOCTOR_ROLE;

SHOW GRANTS TO ROLE HOSPITAL_FINANCE_ROLE;



USE ROLE HOSPITAL_DOCTOR_ROLE;

SELECT * 
FROM HOSPITAL_DATABASE.HOSPITAL_MART.DIM_PATIENT
LIMIT 10;

SELECT *
FROM HOSPITAL_DATABASE.HOSPITAL_MART.FACT_BILLING
LIMIT 10;


USE ROLE HOSPITAL_FINANCE_ROLE;

SELECT *
FROM HOSPITAL_DATABASE.HOSPITAL_MART.FACT_BILLING
LIMIT 10;


USE ROLE HOSPITAL_ADMIN_ROLE;

SELECT *
FROM HOSPITAL_DATABASE.HOSPITAL_MART.DIM_PATIENT
LIMIT 10;