-- CREATE THE USER ADMIN
CREATE OR REPLACE USER HOSPITAL_ADMIN_USER
PASSWORD = 'Admin@123'
DEFAULT_ROLE = HOSPITAL_ADMIN_ROLE
DEFAULT_WAREHOUSE = HOSPITAL_MANAGEMENT_ANALYTICS
MUST_CHANGE_PASSWORD = TRUE;

-- CREATE THE USER DOCTORR
CREATE OR REPLACE USER HOSPITAL_DOCTOR_USER
PASSWORD = 'Doctor@123'
DEFAULT_ROLE = HOSPITAL_DOCTOR_ROLE
DEFAULT_WAREHOUSE = HOSPITAL_MANAGEMENT_ANALYTICS
MUST_CHANGE_PASSWORD = TRUE;

-- CREATE THE USER FINANCE 
CREATE OR REPLACE USER HOSPITAL_FINANCE_USER
PASSWORD = 'Finance@123'
DEFAULT_ROLE = HOSPITAL_FINANCE_ROLE
DEFAULT_WAREHOUSE = HOSPITAL_MANAGEMENT_ANALYTICS
MUST_CHANGE_PASSWORD = TRUE;


-- GRANT THE ROLES TO USER
GRANT ROLE HOSPITAL_ADMIN_ROLE
TO USER HOSPITAL_ADMIN_USER;

GRANT ROLE HOSPITAL_DOCTOR_ROLE
TO USER HOSPITAL_DOCTOR_USER;

GRANT ROLE HOSPITAL_FINANCE_ROLE
TO USER HOSPITAL_FINANCE_USER;


SHOW USERS;
