USE WAREHOUSE HOSPITAL_MANAGEMENT_ANALYTICS;
USE DATABASE HOSPITAL_DATABASE;
USE SCHEMA HOSPITAL_MART;

CREATE OR REPLACE SECURE VIEW SV_PATIENTS AS
SELECT
    PATIENT_ID,
    FULL_NAME,
    PHONE,
    EMAIL,
    CITY,
    STATE,
    REGISTRATION_DATE
FROM DIM_PATIENT;

CREATE OR REPLACE SECURE VIEW SV_APPOINTMENTS AS
SELECT
    APPT_ID,
    APPT_DATE,
    PATIENT_ID,
    DOCTOR_ID,
    DOCTOR_NAME,
    DEPARTMENT,
    SLOT,
    STATUS
FROM FACT_APPOINTMENT;

CREATE OR REPLACE SECURE VIEW SV_BILLING AS
SELECT
    BILL_ID,
    BILL_DATE,
    PATIENT_ID,
    SERVICE_DESC,
    DEPARTMENT,
    NET_AMOUNT,
    PAYMENT_MODE,
    INSURER_NAME
FROM FACT_BILLING;

GRANT SELECT
ON VIEW SV_PATIENTS
TO ROLE HOSPITAL_DOCTOR_ROLE;

GRANT SELECT
ON VIEW SV_APPOINTMENTS
TO ROLE HOSPITAL_DOCTOR_ROLE;

GRANT SELECT
ON VIEW SV_BILLING
TO ROLE HOSPITAL_FINANCE_ROLE;

GRANT SELECT
ON VIEW SV_PATIENTS
TO ROLE HOSPITAL_ADMIN_ROLE;

GRANT SELECT
ON VIEW SV_APPOINTMENTS
TO ROLE HOSPITAL_ADMIN_ROLE;

GRANT SELECT
ON VIEW SV_BILLING
TO ROLE HOSPITAL_ADMIN_ROLE;

CREATE OR REPLACE ROW ACCESS POLICY DEPARTMENT_POLICY
AS (DEPARTMENT STRING)
RETURNS BOOLEAN ->

CASE

    WHEN CURRENT_ROLE() = 'HOSPITAL_ADMIN_ROLE'
    THEN TRUE

    WHEN CURRENT_ROLE() = 'HOSPITAL_DOCTOR_ROLE'
         AND DEPARTMENT IN
         (
             'Cardiology',
             'Neurology'
         )
    THEN TRUE

    WHEN CURRENT_ROLE() = 'HOSPITAL_FINANCE_ROLE'
    THEN TRUE

    ELSE FALSE

END;

ALTER TABLE FACT_APPOINTMENT
ADD ROW ACCESS POLICY DEPARTMENT_POLICY
ON (DEPARTMENT);

ALTER TABLE FACT_APPOINTMENT
CLUSTER BY (APPT_DATE);

ALTER TABLE FACT_BILLING
CLUSTER BY (BILL_DATE);

SHOW VIEWS;

SHOW ROW ACCESS POLICIES;

SHOW MASKING POLICIES;

SHOW ROLES;

SHOW USERS;

USE ROLE HOSPITAL_DOCTOR_ROLE;

SELECT *
FROM SV_PATIENTS
LIMIT 10;

SELECT *
FROM SV_APPOINTMENTS
LIMIT 10;

USE ROLE HOSPITAL_FINANCE_ROLE;

SELECT *
FROM SV_BILLING
LIMIT 10;

USE ROLE HOSPITAL_ADMIN_ROLE;

SELECT *
FROM SV_PATIENTS
LIMIT 10;

SELECT *
FROM SV_APPOINTMENTS
LIMIT 10;

SELECT *
FROM SV_BILLING
LIMIT 10;